# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  ecommerceserviceapi:
    image: ecommerceserviceapi
    build:
      context: .
      dockerfile: eCommerceService.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5053:5053
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
